GetRedshiftRecord:
  handler: src/RedshiftRecord/GetRedshiftRecord/index.handler
  memorySize: 256
  timeout: 900

  environment:
    DB_PORT: ${ssm:/omni-dw/${self:provider.stage}/db/port}
    DB_HOST: ${ssm:/omni-dw/${self:provider.stage}/db/host~true} 
    DB_PASSWORD: ${ssm:/omni-dw/${self:provider.stage}/db/password~true}      
    DB_DATABASE: ${ssm:/omni-dw/${self:provider.stage}/db/name}
    DB_USER: ${ssm:/omni-dw/${self:provider.stage}/db/user~true}
    PROJECT44_TABLE: ${ssm:/omni-dw/${self:provider.stage}/project44/table}
    PROJECT44_ENDPOINT: ${ssm:/omni-project44-api-services/${self:provider.stage}/url}
    PROJECT44_USERNAME: ${ssm:/omni-project44-api-services/${self:provider.stage}/auth/username}
    PROJECT44_PASSWORD: ${ssm:/omni-project44-api-services/${self:provider.stage}/auth/password} 
    DEFAULT_AWS: ${self:provider.region}       
  package:
    include:
    - src/RedshiftRecord/GetRedshiftRecord/**
    - src/shared/**
    - node_modules/**
  events:
    - schedule: rate(30 minutes)