GetRedshiftRecord:
  handler: src/RedshiftRecord/GetRedshiftRecord/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }  
  environment:
    DB_PORT: ${ssm:/omni-dw/devint/db/port}
    DB_HOST: ${ssm:/omni-dw/devint/db/host~true} 
    DB_PASSWORD: ${ssm:/omni-dw/devint/db/password~true}      
    DB_DATABASE: ${ssm:/omni-dw/devint/db/name}
    DB_USER: ${ssm:/omni-dw/devint/db/user~true}
    PROJECT44_TABLE: ${ssm:/omni-dw/devint/project44/table} 
    DEFAULT_AWS: ${self:provider.region}       
  package:
    individually: true
    include:
        - 'src/RedshiftRecord/GetRedshiftRecord/**'
        - 'src/shared/**'
  # events:
  #   - http:
  #       path: records
  #       method: get
  #       cors: true
  #   # - eventBridge:
  #   #    schedule: cron(0/2 * * * ? *)
