OmniJobQueue:
  Type: AWS::Batch::JobQueue
  Properties:
    JobQueueName: omni-dw-project44-job-queue-${self:provider.stage}
    ComputeEnvironmentOrder:
      - Order: 1
        ComputeEnvironment:
          Ref: OmniComputeEnvironment
    State: ENABLED
    Priority: 1