P44JobBatchTaskExecutionRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: omni-dw-project44-taskexec-role-${self:provider.stage}
    AssumeRolePolicyDocument:
      Statement:
      - Effect: Allow
        Principal:
          Service: [ecs-tasks.amazonaws.com]
        Action: ['sts:AssumeRole']
    Path: /
    Policies:
      - PolicyName: AmazonECSTaskExecutionRolePolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - 'ecr:GetAuthorizationToken'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource: '*'
      - PolicyName: omni-dw-project44-batch-task-policy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - 'redshift:*'
              - 'redshift-serverless:*'
            Resource: '*'
      - PolicyName: omni-dw-project44-ecs-task-dynamo-policy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - dynamodb:DescribeTable
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:BatchWriteItem
              - dynamodb:BatchGetItem
            Resource:
              - arn:aws:dynamodb:us-east-1:332281781429:table/omni-dw-project-44-payload-dev

P44JobDefinition:
  Type: AWS::Batch::JobDefinition
  Properties:
    JobDefinitionName: omni-dw-project44-batch-job-definition-${self:provider.stage}
    Type: container
    RetryStrategy:
      Attempts: 1
    PlatformCapabilities:
      - FARGATE
    ContainerProperties:
      Command:
        - node
        - server.js
      ResourceRequirements:
        - Value: 1
          Type: VCPU
        - Value: 2048
          Type: MEMORY
      FargatePlatformConfiguration:
        PlatformVersion: 1.3.0
      LogConfiguration:
        LogDriver: awslogs
        Options:
          awslogs-group: !Ref P44BatchLogGroup
          awslogs-region: !Ref AWS::Region
          awslogs-stream-prefix: omni-dw-project44-batch-logs
      ExecutionRoleArn: !GetAtt 'P44JobBatchTaskExecutionRole.Arn'
      JobRoleArn: !GetAtt 'P44JobBatchTaskExecutionRole.Arn'
      Image: 332281781429.dkr.ecr.us-east-1.amazonaws.com/omni-dw-project44-batch:1
      NetworkConfiguration:
        AssignPublicIp: ENABLED

P44BatchLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: omni-dw-project44-batch-log-group-${self:provider.stage}
    RetentionInDays: 7